import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ArrowRight } from 'lucide-react';
import { Seo } from '@/components/Seo';
import { AdsensePlaceholder } from '@/components/AdsensePlaceholder';
import { blogPosts } from '@/data/blog';
const BlogPage = () => {
    return (_jsxs(_Fragment, { children: [_jsx(Seo, { title: "SEO Blog | Tips, Guides, and News from Seotooler", description: "Stay up-to-date with the latest trends in SEO. Read our expert guides, tips, and case studies to improve your search engine rankings." }), _jsxs("div", { className: "space-y-12", children: [_jsxs("section", { className: "text-center", children: [_jsx("h1", { className: "text-4xl md:text-5xl font-extrabold tracking-tighter mb-4", children: "The Seotooler Blog" }), _jsx("p", { className: "max-w-2xl mx-auto text-lg text-muted-foreground", children: "Your source for expert insights, actionable tips, and the latest news in the world of SEO." })] }), _jsxs("div", { className: "grid lg:grid-cols-3 gap-8", children: [_jsx("div", { className: "lg:col-span-2 space-y-8", children: blogPosts.map((post) => (_jsxs(Card, { className: "overflow-hidden", children: [_jsx(Link, { to: `/blog/${post.slug}`, children: _jsx("img", { src: post.imageUrl, alt: post.title, className: "w-full h-64 object-cover" }) }), _jsxs(CardHeader, { children: [_jsx("div", { className: "flex gap-2 mb-2", children: post.tags.map(tag => _jsx(Badge, { variant: "secondary", children: tag }, tag)) }), _jsx(CardTitle, { children: _jsx(Link, { to: `/blog/${post.slug}`, className: "hover:text-primary transition-colors", children: post.title }) }), _jsxs(CardDescription, { children: [post.author, " \u2022 ", post.date] })] }), _jsx(CardContent, { children: _jsx("p", { className: "text-muted-foreground", children: post.description }) }), _jsx(CardFooter, { children: _jsxs(Link, { to: `/blog/${post.slug}`, className: "flex items-center font-semibold text-primary hover:underline", children: ["Read More ", _jsx(ArrowRight, { className: "ml-2 h-4 w-4" })] }) })] }, post.slug))) }), _jsxs("aside", { className: "lg:col-span-1 space-y-8", children: [_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsx(CardTitle, { children: "Categories" }) }), _jsx(CardContent, { children: _jsxs("ul", { className: "space-y-2", children: [_jsx("li", { children: _jsx(Link, { to: "#", className: "text-muted-foreground hover:text-foreground", children: "SEO Basics" }) }), _jsx("li", { children: _jsx(Link, { to: "#", className: "text-muted-foreground hover:text-foreground", children: "Keyword Research" }) }), _jsx("li", { children: _jsx(Link, { to: "#", className: "text-muted-foreground hover:text-foreground", children: "Link Building" }) }), _jsx("li", { children: _jsx(Link, { to: "#", className: "text-muted-foreground hover:text-foreground", children: "Technical SEO" }) })] }) })] }), _jsx(AdsensePlaceholder, { height: 600 })] })] })] })] }));
};
export default BlogPage;
